<div class="ramadan-widget">
    <div class="container" style="direction: rtl">
            <form id="ramadan">
                <label><?php _e('اختر بلدك ', RAMADANWIDGET_TEXT_DOMAIN);?></label>
                <select name="country" id="country">
                    <option value="United Arab Emirates" ><?php _e('الإمارات العربية المتحدة', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Lebanon"><?php _e('لبنان', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Algeria"><?php _e(' الجزائر', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Bahrain"><?php _e('البحرين', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="the Comoros Islands"><?php _e('جزر القمر', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Djibouti"><?php _e('جيبوتي', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Egypt"><?php _e('مصر', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Iraq"><?php _e('العراق', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Kuwait"><?php _e('الكويت', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Libya"><?php _e('ليبيا', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Morocco"><?php _e('المغرب', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Mauritania"><?php _e('موريتانيا', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Oman"><?php _e('عمان', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Palestine"><?php _e('فلسطين', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Qatar"><?php _e('قطر', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Saudi Arabia"><?php _e('السعودية', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Somalia"><?php _e('الصومال', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Sudan"><?php _e('السودان', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Syria"><?php _e('سوريا', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Tunisia"><?php _e('تونس', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Yemen"><?php _e('اليمن', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                    <option value="Jordan"><?php _e('الأردن', RAMADANWIDGET_TEXT_DOMAIN); ?></option>
                </select>
                <button type="submit"><?php _e('إرسال ', RAMADANWIDGET_TEXT_DOMAIN);?></button>
            </form>
            <div class="results"></div>
        </div>
    </div>