<?php

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key'                   => 'group_5ae3770664bc3',
        'title'                 => 'Homepage custom fields',
        'fields'                => array(
            array(
                'key'               => 'field_5ae3770fcea12',
                'label'             => 'Video type',
                'name'              => 'video_type',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'choices'           => array(
                    'youtube' => 'youtube',
                    'vimeo'   => 'vimeo',
                ),
                'default_value'     => array(
                ),
                'allow_null'        => 0,
                'multiple'          => 0,
                'ui'                => 0,
                'ajax'              => 0,
                'return_format'     => 'value',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5ae37751cea13',
                'label'             => 'Homepage Video id',
                'name'              => 'homepage_video_id',
                'type'              => 'text',
                'instructions'      => 'Place the id of the video',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5ae3775acea14',
                'label'             => 'Video image',
                'name'              => 'video_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'array',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_5ae37771cea15',
                'label'             => 'Mobile video image',
                'name'              => 'mobile_video_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'array',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_5ae37784cea16',
                'label'             => 'About text',
                'name'              => 'about_text',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => '',
                'new_lines'         => '',
            ),
            array(
                'key'               => 'field_5ae377af4581b',
                'label'             => 'Custom service title',
                'name'              => 'custom_service_title',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5ae39ccac0872',
                'label'             => 'Registered trademark',
                'name'              => 'registered_trademark',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 1,
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_5ae377bb4581c',
                'label'             => 'Custom service subtitle',
                'name'              => 'custom_service_subtitle',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5ae377c44581d',
                'label'             => 'Custom service description',
                'name'              => 'custom_service_description',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5ae377cf4581e',
                'label'             => 'Custom service advantages',
                'name'              => 'custom_service_advantages',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_5ae377ec4581f',
                        'label'             => 'Descriptive title',
                        'name'              => 'descriptive_title',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_5ae3783b45820',
                        'label'             => 'Descriptive text',
                        'name'              => 'descriptive_text',
                        'type'              => 'textarea',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'maxlength'         => '',
                        'rows'              => '',
                        'new_lines'         => '',
                    ),
                    array(
                        'key'               => 'field_5ae3787445821',
                        'label'             => 'Descriptive image',
                        'name'              => 'descriptive_image',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'return_format'     => 'array',
                        'preview_size'      => 'thumbnail',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_5ae45414ddec8',
                'label'             => 'Menu background',
                'name'              => 'menu_background',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'array',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_5ae455c596c07',
                'label'             => 'Mobile menu background',
                'name'              => 'mobile_menu_background',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'array',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_5ae45422ddec9',
                'label'             => 'Menu',
                'name'              => 'menu',
                'type'              => 'file',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'array',
                'library'           => 'all',
                'min_size'          => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_5ae457ce2a3ec',
                'label'             => 'Menu image',
                'name'              => 'menu_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'array',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_5ae48d4fb8cad',
                'label'             => 'Treatment videos',
                'name'              => 'treatment_videos',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_5ae48d61b8cae',
                        'label'             => 'Video title',
                        'name'              => 'video_title',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_5ae48d73b8caf',
                        'label'             => 'video id',
                        'name'              => 'video_id',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_5ae48fb775168',
                        'label'             => 'Video type',
                        'name'              => 'video_type',
                        'type'              => 'select',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'choices'           => array(
                            'youtube' => 'youtube',
                            'vimeo'   => 'vimeo',
                        ),
                        'default_value'     => array(
                        ),
                        'allow_null'        => 0,
                        'multiple'          => 0,
                        'ui'                => 0,
                        'ajax'              => 0,
                        'return_format'     => 'value',
                        'placeholder'       => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_5ae62d643b9e3',
                'label'             => 'storyies section title',
                'name'              => 'stories_section_title',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5ae62d753b9e4',
                'label'             => 'stories section subtitle',
                'name'              => 'stories_section_subtitle',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5ae62d2a3b9df',
                'label'             => 'Stories',
                'name'              => 'stories',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_5ae62d393b9e0',
                        'label'             => 'Story image',
                        'name'              => 'story_image',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'return_format'     => 'array',
                        'preview_size'      => 'thumbnail',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                    ),
                    array(
                        'key'               => 'field_5ae62d4e3b9e1',
                        'label'             => 'Story title',
                        'name'              => 'story_title',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_5ae62d573b9e2',
                        'label'             => 'story subtitle',
                        'name'              => 'story_subtitle',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_5ae6db1b51986',
                'label'             => 'Booking form shortcode',
                'name'              => 'booking_form_shortcode',
                'type'              => 'text',
                'instructions'      => 'Paste form shortcode in this field',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5ae74e4b7e6c8',
                'label'             => 'Clinic section subtitle',
                'name'              => 'clinic_section_subtitle',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5ae74e567e6c9',
                'label'             => 'emirates clinic address',
                'name'              => 'emirates_clinic_address',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_5ae74e9f7e6ca',
                        'label'             => 'Address city',
                        'name'              => 'address_city',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_5ae74ec57e6cb',
                        'label'             => 'Address details',
                        'name'              => 'address_details',
                        'type'              => 'textarea',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'maxlength'         => '',
                        'rows'              => '',
                        'new_lines'         => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_5ae74f2b7e6cc',
                'label'             => 'england clinic address',
                'name'              => 'england_clinic_address',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_5ae74f2b7e6cd',
                        'label'             => 'Address city',
                        'name'              => 'address_city',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_5ae74f2b7e6ce',
                        'label'             => 'Address details',
                        'name'              => 'address_details',
                        'type'              => 'textarea',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'maxlength'         => '',
                        'rows'              => '',
                        'new_lines'         => '',
                    ),
                ),
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_template',
                    'operator' => '==',
                    'value'    => 'page-homepage.php',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ));

endif;
