<?php

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key'                   => 'group_5ae9b51914009',
        'title'                 => 'Service details cf',
        'fields'                => array(
            array(
                'key'               => 'field_5aecd2ba076c6',
                'label'             => 'Icon',
                'name'              => 'icon',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'array',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_5aecdc79440e2',
                'label'             => 'Sub services listing type',
                'name'              => 'sub_services_listing_type',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'choices'           => array(
                    'block_listing'    => 'Block Listing',
                    'detailed_listing' => 'Detailed Listing',
                ),
                'default_value'     => array(
                ),
                'allow_null'        => 0,
                'multiple'          => 0,
                'ui'                => 0,
                'ajax'              => 0,
                'return_format'     => 'value',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5aecd2ee9afcd',
                'label'             => 'Sections',
                'name'              => 'sections',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_5aecdc79440e2',
                            'operator' => '==',
                            'value'    => 'detailed_listing',
                        ),
                    ),
                ),
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_5aecd2f99afce',
                        'label'             => 'Section title',
                        'name'              => 'section_title',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_5aecd2ff9afcf',
                        'label'             => 'Section Content',
                        'name'              => 'section_content',
                        'type'              => 'repeater',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'collapsed'         => '',
                        'min'               => 0,
                        'max'               => 0,
                        'layout'            => 'row',
                        'button_label'      => '',
                        'sub_fields'        => array(
                            array(
                                'key'               => 'field_5aecd30d9afd0',
                                'label'             => 'Title',
                                'name'              => 'title',
                                'type'              => 'text',
                                'instructions'      => '',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'default_value'     => '',
                                'placeholder'       => '',
                                'prepend'           => '',
                                'append'            => '',
                                'maxlength'         => '',
                            ),
                            array(
                                'key'               => 'field_5aecd3119afd1',
                                'label'             => 'Text',
                                'name'              => 'text',
                                'type'              => 'textarea',
                                'instructions'      => '',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'default_value'     => '',
                                'placeholder'       => '',
                                'maxlength'         => '',
                                'rows'              => '',
                                'new_lines'         => '',
                            ),
                        ),
                    ),
                    array(
                        'key'               => 'field_5aecd3269afd2',
                        'label'             => 'Link',
                        'name'              => 'link',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'service',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ));

endif;

